### PR TITLE
add GitHub action to autogenerate WMO codelist XML

### PR DESCRIPTION
**Pull request by tomkralidis**
This PR introduces a GitHub action to autogenerate the WMO Codelist XML that is currently at https://github.com/wmo-im/wmcp/blob/master/codelists/WMOCodeLists.xml

On merged pull requests and commits, the action will read all CSVs in `codelists` and generate the WMO Code list catalogue XML document in `dist/WMOCodeLists.xml`.

We will need to discuss how to do official releases (version, date, etc.)

cc @efucile @amilan17

### CODE REVIEW

**Comment by tomkralidis** [comment]
cc @josusky for review as well.  I'm not sure why the actions/workflow is failing, fwiw.  This may or may resolved once the PR is approved/merged (if there is consensus on the approach, that is).

**Comment by josusky** [comment]
Sorry, I am a bit confused. Were can I find the tools that do the auto-generation. I have cloned this repository (https://github.com/wmo-im/wmcp) but there is no ".github/workflows/codelist-catalogue.yml" or "scripts/generate-codelist-catalogue.py".
Oh, I have found "codelist-catalogue.yml" in "https://github.com/tomkralidis/wmcp.git" but I am still confused.
Apparently, I am not the right reviewer for github workflows. I am an old school guy, I would prefer to generate the codelist using something I can run on my own machine and check the result before publishing it :-)

**Comment by josusky** [comment]
Hi Tom, thanks for explanation. I still don't fully understand the code list generation but that is not your fault.
Anyway, I have one suggestion for change in the "generate-codelist-catalogue.py" to ensure equal results on different systems - sort the list of CSV files, i.e. do something like:
`file_list = glob.glob('codelists/*.csv')
file_list.sort()
for cl in file_list:`

**Comment by martaguti** [comment]
Hi, 
Question : we (humans ) will be maintaining the csv files and generate automatically the WMOCodeLists.xml 
I created the CSV's from WMOCodeLists.xml . (the other way around)

So I guess we should agree what is the official working base ( csv or WMOCodeLists.xml).
Not that it changes very often :-)

**Comment by tomkralidis** [comment]
@josusky thanks, good catch, fixed.  Also, as per our discussion on Slack:
- version number fixed to `1.3.dev0`
- versionDate is `YYYY-MM-DD`

I would see both of these being set once we have something ready to release/tag.

**Comment by tomkralidis** [comment]
@martaguti thanks for the info, very good point.  Is there any objection to the CSVs being the official working base?  Managing the CSVs and creating the XML (other other complex) output is consistent with how codelists are managed in other WMO TT's (such as [TT-TDCF](https://github.com/wmo-im/grib2), etc.), and (I'm guessing) easier to manage.

Does this makes sense?  We can also ask the team in the discussion forum if that helps, or announce the workflow once we have consensus here.

**Review by josusky — APPROVED** [review]

**Review by josusky — APPROVED** [review]

**Comment by martaguti** [comment]
@tomkralidis  that makes sense as csv easier to mantain. ( if that is also consistent with how  codelists are managed in other TT's)

It would be great to document the workflow and how to release

**Comment by tomkralidis** [comment]
@martaguti I've drafted some workflow for codelists for review: https://github.com/wmo-im/wmcp/wiki/ReleaseManagement#codelists.  Note that once the codelists go into a dedicated GitHub repository then the links in the workflow will be updated.

**Comment by martaguti** [comment]
That looks great !
thanks @tomkralidis

**Pull request merged**
